config/routes.rb
Rails.application.routes.draw do
  devise_for :athletes
  devise_scope :athlete do
    authenticated :athlete do
      root 'interfaces#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :interfaces, only: [:index,:edit]

  namespace :api do
    namespace :v1 do
      resources :athletes
      resources :sports
      resources :exercises
      resources :equipments
      resources :practices
      resources :signups
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/athletes_controller.rb
class Api::V1::AthletesController < ApplicationController

  def index
    render json: Athlete.find(current_athlete.id)
  end

  def update
    @athlete = Athlete.find(athlete_edit_params["id"])
    @athlete.latitude = athlete_edit_params["latitude"]
    @athlete.longitude = athlete_edit_params["longitude"]
    if @athlete.save
      render json: @athlete
      else
      render interfaces_path
    end
  end



def athlete_edit_params
  params.require(:athlete).permit(:id,:latitude,:longitude)
end

end

app/controllers/api/v1/equipments_controller.rb
class Api::V1::EquipmentsController < ApplicationController

  def create
    @equipment = Equipment.new(equipment_params)
    if @equipment.save
      render json: @equipment
    else
      redirect_to "/"
    end
  end

  def destroy
    @equipment = Equipment.find(params["id"])
    if @equipment.destroy
      render json: Equipment.all
    else
      redirect_to "/"
    end
  end

  private

  def equipment_params
    params.require(:equipment).permit(:name,:athlete_id)
  end
end

app/controllers/api/v1/exercises_controller.rb
class Api::V1::ExercisesController < ApplicationController

  def create
    @exercise = Exercise.new(exercise_params)
    if @exercise.save
      render json: Sport.find(exercise_params[:sport_id])
    else
      redirect_to "/"
    end
  end

  def destroy
    @exercise = Exercise.find(params["id"])
    @sport = Sport.find(@exercise.sport_id)
    if @exercise.destroy
      render json: @sport
    else
      redirect_to '/'
    end
  end

  private

  def exercise_params
    params.require(:exercise).permit(:sport_id,:athlete_id)
  end
end

app/controllers/api/v1/practices_controller.rb
class Api::V1::PracticesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_athlete!

  def index
    render json: Practice.all
  end

  def create
    @practice = Practice.new(practice_params)
    @practice.athlete_id = current_athlete.id
    if @practice.save
      signup = Signup.new
      signup.athlete_id = current_athlete.id
      signup.practice_id = @practice.id
      signup.owner = true
      signup.save
      render json: @practice
    else
      redirect_to "/"
    end
  end

  private

  def practice_params
    params.require(:practice).permit(:location, :latitude, :longitude, :date_time, :sport_id)
  end


end

app/controllers/api/v1/signups_controller.rb
class Api::V1::SignupsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_athlete!

  def create
    signup = Signup.new
    signup.athlete_id = current_athlete.id
    signup.practice_id = signup_params[:practice_id]
    if signup.save
      render json: signup
    else
      redirect '/'
    end
  end

  def index
    @athlete = Athlete.find(current_athlete.id)
    @athlete_practices = @athlete.practices
    render json: @athlete_practices
  end

  private

  def signup_params
    params.require(:signup).permit(:practice_id)
  end
end

app/controllers/api/v1/sports_controller.rb
class Api::V1::SportsController < ApplicationController
  before_action :authenticate_athlete!

  def index
    render json: Sport.all
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.

 protect_from_forgery unless: -> { request.format.json? }

 before_action :configure_permitted_parameters, if: :devise_controller?

 protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
 end
end

app/controllers/interfaces_controller.rb
class InterfacesController < ApplicationController
  before_action :authenticate_athlete!

  def index

  end

end

app/views/interfaces/index.html.erb
<nav class="top-bar">
<ul class="title-area">
  <li class="name">
    <h1><a id="navbar-text" href="/">REPITITIONS</a></h1>
  </li>
</ul>

<section  id="sign" class="top-bar-section">
  <ul class="right">
    <%- if current_athlete -%>
      <li class="line-items-for-session"><%= link_to 'SIGN OUT', destroy_athlete_session_path, method: :delete %></li>
    <%- else -%>
      <li class="line-items-for-session"id="sign-up"><%= link_to 'SIGN UP', new_athlete_registration_path %></li>
      <li><%= link_to 'SIGN IN', new_athlete_session_path %></li>
    <%- end -%>
  </ul>
</section>
<script type="text/javascript" src=<%="https://maps.googleapis.com/maps/api/js?key=#{ENV["GOOGLE_MAPS_API"]}&libraries=places"%>></script>
</nav>
<div id="app"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Repetition</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>

    <%= javascript_include_tag "vendor/modernizr" %>

  <%= csrf_meta_tags %>
</head>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
<body>


  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>

  <%- if Rails.env.development? || Rails.env.test? -%>
    <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'
    <%- end -%>
  <%- end -%>
  <%= javascript_pack_tag 'application' %>

  <%= yield :extra_footer %>
</body>
</html>